name: Deploy to staging
permissions:
  contents: read
  packages: write
on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy-staging:
    name: Call reusable workflow when pull request is created
    if: github.event.pull_request.draft == false
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-deploy.yaml@main
    with:
      app_name: fdk-nginx-sparql
      environment: staging
      cluster: digdir-fdk-dev
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
